### PR TITLE
Don't use custom icon for panel

### PR DESCRIPTION
**Pull request by zagortenay333**
- Also adds new style classes to style the new icon

### CODE REVIEW

**Comment by axos88** [comment]
Overall, this looks good, a few things that stand out:
  - i don't quite like the icon. Where can the list of available icons be found, maybe there is something that looks better?
  - does cinnamon support animations? Instead of changing the color, a shaking animation may be preferred, or even the old, inverting approach
  - the old icon files should be deleted from the repo if they are no longer used

**Comment by zagortenay333** [comment]
Yeah forgot about those icons. Removed.

The icon that is used now is part of the default icon-theme you are using, and it's semantically accurate (the name of the icon is `alarm`). This way it'll be consistent in style with the rest of the icon theme.

I think the `tweener` file might have functions that could be use d for animation. No clue.

**Comment by axos88** [comment]
Thanks. I meant CSS3 animations. Do you know anything about wether they are supported or not?

**Comment by zagortenay333** [comment]
Oh, no. The css here is extremely limited unfortunately.

**Comment by axos88** [comment]
Yeah, suspected as much. I will merge this and do a release shortly.

**Comment by axos88** [comment]
Thank you for your contribution. I opened PR https://github.com/linuxmint/cinnamon-spices-applets/pull/61

**Pull request merged**
